### ISSUE TITLE
Re-evaluate usage of Utf8JsonReader.ValueSpan for property name equality via SequenceEqual of raw bytes

### ISSUE THREAD

**Issue by ahsonkhan** [ycrumeyrolle/Jwt#317]
https://github.com/ycrumeyrolle/Jwt/blob/59bace31afecca486d80cfb87f40db5fdbec4cd8/src/OpenIdConnect/Address.cs#L39-L45
This type of comparison of the raw bytes (using ValueSpan) will not always work and miss property names that are "equal" but **contain escaped characters.**

Is this expected/fine? If not, consider using `ValueTextEqual` APIs t do the property name comparisons. Generally speaking, getting the raw bytes via `ValueSpan` and then using `SequenceEqual` probably isn't what you want to do unless you control the input or only want to support the exact bytes.

https://github.com/dotnet/corefx/blob/d3911035f2ba3eb5c44310342cc1d654e42aa316/src/System.Text.Json/ref/System.Text.Json.cs#L316-L318
https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonreader.valuetextequals?view=netcore-3.0#System_Text_Json_Utf8JsonReader_ValueTextEquals_System_ReadOnlySpan_System_Byte__

**For instance:**
If the json payload contained `formatted` this comparison will work fine, but it wouldn't work for `\\u0066ormatted` (f == \\u0066).
Something to consider.

I would double check usage of `reader.ValueSpan` property in other instances as well (where the comparison is being deferred (when saved in `JwtProperty`, etc.).
https://github.com/ycrumeyrolle/Jwt/search?utf8=%E2%9C%93&q=ValueSpan&type=
Like: https://github.com/ycrumeyrolle/Jwt/blob/90431793b0419333d1f47467192b3361f6c76e39/src/JsonWebToken/JwtObject.cs#L188

Also, is the JSON input here trusted or known to be valid UTF-8?

cc @ycrumeyrolle

**Comment by ycrumeyrolle** [comment]
> Generally speaking, getting the raw bytes via `ValueSpan` and then using `SequenceEqual` probably isn't what you want to do unless you control the input or only want to support the exact bytes.

I want to support the exact match as the propertie names are registred values. 
But... 
as defined in the [JWS RFC](https://tools.ietf.org/html/rfc7515#section-10.13), 
> For security reasons, the representations of these names must be compared verbatim after performing any escape processing

So I have to support escaped properties.
The properties detection may be rewrite with `ValueTextEqual` instead of bytes comparison as proposed. 

> Also, is the JSON input here trusted or known to be valid UTF-8?

The JSON input is not trusted at all. Even if there is a signature validation, we have to read a part of the JSON before.
 
It should be a valid UTF-8 encoded string, but it may be a malicious string.
Do you have any example of malformed UTF-8 that may cause security issue?

**Comment by ahsonkhan** [comment]
> It should be a valid UTF-8 encoded string, but it may be a malicious string.

What do you mean by malicious?

> Do you have any example of malformed UTF-8 that may cause security issue?

I don't know. I would assume yes. Within the context of matching for equality on known utf8 bytes, it shouldn't matter.

**Comment by ycrumeyrolle** [comment]
Fixed by #325
