### ISSUE TITLE
Help to create JWT token from JWK

### ISSUE THREAD

**Issue by Alaximo** [ycrumeyrolle/Jwt#432]
Hello. 
How can I use your library to create an JWT token with Elliptic Curve JSON Web Key?

private const string privkey =
            "{\"kty\":\"EC\",\"alg\":\"ES256\",\"crv\":\"P-256\"," +            "\"x\":\"lmzBhWRXSZTx5q6b80PK_GL7b94YYXI1hNB3YdJ6bzQ\",\"y\":\"sXwmQX8sAm5yoybyq0RvMMhQp7Ox4lvhdpy_xPjfs58\"," +"\"d\":\"P_MepPu0IPJEIQ_WUL5p12qb-phfMBdiDC8vHgdwvJ4\"}";

None of the methods does not work:
1.
var privJwk = new ECJwk(256, "P_MepPu0IPJEIQ_WUL5p12qb-phfMBdiDC8vHgdwvJ4","lmzBhWRXSZTx5q6b80PK_GL7b94YYXI1hNB3YdJ6bzQ","sXwmQX8sAm5yoybyq0RvMMhQp7Ox4lvhdpy_xPjfs58");
2.
var privJwk = ECJwk.FromJson(privkey);

**Comment by ycrumeyrolle** [comment]
Both methods are functionnal:
```
            var privJwk1 = new ECJwk(EllipticalCurve.P256, "P_MepPu0IPJEIQ_WUL5p12qb-phfMBdiDC8vHgdwvJ4", "lmzBhWRXSZTx5q6b80PK_GL7b94YYXI1hNB3YdJ6bzQ", "sXwmQX8sAm5yoybyq0RvMMhQp7Ox4lvhdpy_xPjfs58", SignatureAlgorithm.EcdsaSha256);
            var privJwk1bis = new ECJwk(EllipticalCurve.P256, d: "P_MepPu0IPJEIQ_WUL5p12qb-phfMBdiDC8vHgdwvJ4", x: "lmzBhWRXSZTx5q6b80PK_GL7b94YYXI1hNB3YdJ6bzQ", y: "sXwmQX8sAm5yoybyq0RvMMhQp7Ox4lvhdpy_xPjfs58", SignatureAlgorithm.EcdsaSha256);
            var privJwk2 = ECJwk.FromJson("{\"kty\":\"EC\",\"alg\":\"ES256\",\"crv\":\"P-256\"," + "\"x\":\"lmzBhWRXSZTx5q6b80PK_GL7b94YYXI1hNB3YdJ6bzQ\",\"y\":\"sXwmQX8sAm5yoybyq0RvMMhQp7Ox4lvhdpy_xPjfs58\"," + "\"d\":\"P_MepPu0IPJEIQ_WUL5p12qb-phfMBdiDC8vHgdwvJ4\"}");
```

Then you can follow the sample [here](https://github.com/ycrumeyrolle/Jwt/blob/master/samples/JwsCreationSample/Program.cs) by remplacing the `SymmetricJwk` by the `ECJwk`.

**Comment by Alaximo** [comment]
I get errors in both ways. As if the library was installed incorrectly. I'm using visual studio 2019. The library is installed via NuGet. What did I do wrong?
1.  var privJwk1 = new ECJwk(EllipticalCurve.P256,...........)
getting an error -  ""ECJwk" does not contain a constructor that accepts arguments 5"
2.  var privJwk2 = ECJwk.FromJson("{\"kty\":\................);
after compilation I get an error - "JWK type 'EC is not supported'"
![ECJwk](https://user-images.githubusercontent.com/39144282/81035069-22accd00-8ebb-11ea-8271-ac03091ec1c0.png)
![ECJwk2](https://user-images.githubusercontent.com/39144282/81035073-27718100-8ebb-11ea-81e7-4f83ebf1170f.png)
![ECJwk3](https://user-images.githubusercontent.com/39144282/81035075-2a6c7180-8ebb-11ea-9349-3bce546b69d2.png)

**Comment by ycrumeyrolle** [comment]
I assume you are target the .Net Framework and not .Net Core. 

I will take a look on the reason of the exclusion of the elliptic curves related algorithms on tfm net461.

**Comment by ycrumeyrolle** [comment]
What is your version of the Framework ?

**Comment by Alaximo** [comment]
Thank you for responding quickly. I use Framework 4.7.2

**Comment by ycrumeyrolle** [comment]
The latest verion 1.4 of the package now explicitely support net47, with elliptic curve support.

**Comment by Alaximo** [comment]
Thanks!! Everything worked

**Comment by Alaximo** [comment]
Another question - is your package free?

**Comment by ycrumeyrolle** [comment]
You just have to follow the [licence](https://github.com/ycrumeyrolle/Jwt/blob/master/LICENSE)

**Comment by Alaximo** [comment]
Thanks. I have no more questions.
