### ISSUE TITLE
How to get payload decryption json?

### ISSUE THREAD

**Issue by orangeagain** [ycrumeyrolle/Jwt#503]

**Comment by orangeagain** [comment]
My current resolvent is decryption whole JWT.so i closet this issues

**Comment by ycrumeyrolle** [comment]
@orangeagain Can your share your solution? 
Is it an issue with documentation?

**Comment by orangeagain** [comment]
> @orangeagain Can your share your solution?
> Is it an issue with documentation?

I Plan to encrypt whole token like this:
RAW:
{"alg": "HS256","typ": "JWT"}.{  "sub": "1234567890",  "name": "John Doe",  "iat": 1516239022}

after encrypt:
{"alg": "HS256","typ": "JWT"}.ENCRYPTPAYLOAD

final,after signature:
{"alg": "HS256","typ": "JWT"}.ENCRYPTPAYLOAD.SIGNATURE

I find different implement in your code. 
but you didn't throw decryption payload,you just valid it. 
can you throw payload json in decryption process?

JWT struct:
header.PAYLOAD.signature

**Comment by orangeagain** [comment]
Throw payload json because I need read custom jsonobj
[](https://github.com/ycrumeyrolle/Jwt/issues/498)

**Comment by orangeagain** [comment]
I found a way.thank you
https://github.com/ycrumeyrolle/Jwt/blob/master/samples/BinaryJwtCreationSample/Program.cs
https://github.com/ycrumeyrolle/Jwt/blob/master/samples/JweValidationSample/Program.cs

**Comment by ycrumeyrolle** [comment]
You are right. If you need to encrypt a JWS, this is basicaly a JWE.
